spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://chunodb.cgnrtbr54etn.ap-northeast-2.rds.amazonaws.com:3306/chuno?serverTimezone=UTC&characterEncoding=UTF-8
#    username: kimdragonhee
#    password: dydrkfl1
    edriver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mysql://34.80.151.71:30288/spweather?serverTimezone=Asia/Seoul
    username: root
    password: new1234!


  kafka:
    bootstrap-servers: 35.201.210.192:9094
    consumer:
      group-id: dragon2-kafka
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


