apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-0
spec:
  storageClassName: ""            # 1. 다이나믹 프로비저닝을 사용하지 않음을 명시합니다.
  accessModes:
    - ReadWriteOnce               # 2. accessMode가 ReadWriteOnce 인 PV를 선택합니다.
  resources:
    requests:
      storage: 5Gi                # 3. 스토리지의 크기가 5GB보다 큰 PV를 선택합니다.
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-0
spec:
  storageClassName: ""            # 1. 다이나믹 프로비저닝을 사용하지 않음을 명시합니다.
  accessModes:
    - ReadWriteOnce               # 2. accessMode가 ReadWriteOnce 인 PV를 선택합니다.
  resources:
    requests:
      storage: 5Gi                # 3. 스토리지의 크기가 5GB보다 큰 PV를 선택합니다.
