apiVersion: v1
kind: Service
metadata:
  name: sapoon-weather-batch
  labels:
    app: sapoon-weather-batch
    service: sapoon-weather-batch
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: sapoon-weather-batch
