spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://chunodb.cgnrtbr54etn.ap-northeast-2.rds.amazonaws.com:3306/chuno
    #username: kimdragonhee
    #password: dydrkfl1
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://35.194.192.57:30208
    username: root
    password: new1234!
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gcp:
      credentials:
        location: /Users/wonhyeongcho/Development/sapoon/back/community-service/sapoon-8f1667474a97.json
      storage:
        bucket: spaoon-community-service
        credentials:
          location: /Users/wonhyeongcho/Development/sapoon/back/community-service/sapoon-8f1667474a97.json

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: sapoon.communityservice.vo