spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  mail:
    host: smtp.gmail.com
    port: 587
    username: sapoon0521
    password: eldptmtkvns
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sapoon.loginmembservice.vo
