spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sapoon.loginmembservice.vo
